### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by jhepam** [nathancahill/split#193]
Hi,

Is it possible to animate the split panel so when the panel size is set the panels slowly opens.

Jake

**Comment by forger** [comment]
I support this feature request! I end up using setSizes() a lot to adjust one split panel to fit its contents. Doing so without animation makes the UX a bit jerky without. I tried to use CSS3 transition on the split panels but did not succeed and can't tell why. Maybe it's the way the style properties are set in setElementSize()? https://github.com/nathancahill/split/blob/3eed35a8c840ff205781c5e92eae5e17d595ec26/packages/splitjs/src/split.js#L214

Or maybe I'm using it wrong? Do you have an example in the wild that animates the size change?

**Comment by forger** [comment]
Looking a bit deeper, maybe supplying an override for https://github.com/nathancahill/split/tree/master/packages/splitjs#elementstyle is the solution? Although I'm not sure what implementation choices we really have there.

**Comment by nathancahill** [comment]
Yes, this should be possible to do with CSS animations and the `elementStyle` hook.

**Comment by forger** [comment]
never mind, mate. browser cache got me. It definitely works with like this:
```js
var split = Split(['#main', '#drawer'];
split.setSizes([50,50]);
split.setSizes([10,90]);
```

```CSS
     #main, #drawer {
        overflow: auto;
        position: relative;

        .transistion (@what){
            transition: @what;
            -webkit-transition: @what;
            -moz-transition: @what;
        }

        .transistion(width 1s ease);
        .transistion(height 1s ease);
    }
```

**Comment by nathancahill** [comment]
Cool!

**Comment by forger** [comment]
The above minimalist example reacts rather sluggish when being dragged. A small modification like this takes care of that.
```js
var split = Split(['#main', '#drawer'], {
    onDragStart: function () { $('#main,#drawer').addClass("dragged"); },
    onDragEnd: function () { $('#main,#drawer').removeClass("dragged"); }
});

split.setSizes([50,50]);
split.setSizes([10,90]);
```

```CSS
     #main, #drawer {
        overflow: auto;
        position: relative;

        .transition (@what){
            transition: @what;
            -webkit-transition: @what;
            -moz-transition: @what;
        }

        &:not(.dragged) {
            .transition(width 1s ease);
            .transition(height 1s ease);
        }
    }
```
Thanks @nathancahill and keep up the good work!
