### ISSUE TITLE
Embedded Ace editor gets wrong panel width

### ISSUE THREAD

**Issue by jtlapp** [nathancahill/split#355]
I have played with about a dozen split panel solutions, and this one is my favorite. But I have not been able to get it to work with the [Ace editor](https://ace.c9.io/), and now I'm sad that I may need to find another solution. I suspect the problem is in Ace, but split is definitely doing something unusual that Ace isn't handling well, so I'm hoping that you split folks might have some insight.

I get strange behavior embedding [`react-ace`](https://github.com/securingsincity/react-ace#readme) in `react-split`. Here I've embedded two editors in two panes and typed `let x = "this line got scrolled left"` into the first line of the first pane:

![Screen Shot 2020-09-01 at 17 25 20](https://user-images.githubusercontent.com/138133/92011841-466d0c00-ed11-11ea-8eec-452a5bc15a38.png)

While typing code, as soon as I hit the right-most margin of the text found in the yellow header div that precedes the editor, Ace starts scrolling the line to the left as I type. I am able to subsequently scroll the text back into view, but Ace won't let me position the cursor to the right of this point in the editor.

If I remove the preceding yellow header from each pane, Ace behaves as if this scrolling point is the very first character and thus never lets me see the characters I type.

It's as if the browser thinks that the pane has one width and Ace thinks it has another width, that latter width being the minimum width needed to display anything else also in the pane with the editor.

Here is my React, implemented with [nextjs](https://nextjs.org/):

```tsx
import Split from 'react-split'
import AceEditor from 'react-ace'
import 'brace/mode/javascript'

export default function Home() {
  return (
    <main className="outermost">
      <Split
        className="my_split"
        sizes={[50, 50]}
        minSize={100}
        expandToMin={false}
        gutterSize={10}
        gutterAlign="center"
        snapOffset={0}
        direction="horizontal"
      >
        <CodePane id="left_pane" />
        <CodePane id="right_pane" />
      </Split>
    </main>
  )
}

function CodePane(props: {id: string}) {
  return <div id={props.id} className="code_pane">
    <div className="pane_header">Right code margin |</div>
    <AceEditor
      name={props.id + "_editor"}
      mode="javascript"
      height="100%"
      width="100%"
    />
  </div>;
}
```

And here is my CSS:

```css
body {
  padding: 0;
  margin: 0;
}

* {
  box-sizing: border-box;
}

.outermost {
  width: 100%;
  height: 100vh;
  background-color: darkblue;
  padding: 20px;
}

.my_split {
  display: flex;
  flex-direction: row;
  width: 100%;
  height: 100%;
  background-color: lightgray;
}

.pane_header {
  background-color: yellow;
  width: 100%;
  height: 20px;
}

.code_pane {
  height: 100%;
  background-color: red;
}

.split,
.gutter.gutter-horizontal {
  height: 100%;
}
```

I attempted to implement the CSS recommendations found in the split docs. I've also implemented this with `float:left` and get the same problem. I may have gotten things wrong, as I wasn't clear what all needed to be done.

Do you have any suggestions for how I might get this working?
