### ISSUE TITLE
HOWTO: Getting started with react-split-grid

### ISSUE THREAD

**Issue by anjalikk14** [nathancahill/split#362]
(This may not belong as an issue but wasn't sure where else to put it)

I spent way too long trying to figure out how to get a minimal working example with react-split-grid. I finally got something working, so figured I'd share. 

CSS:

```css
.gutter {
  background-color: #eee;
  background-repeat: no-repeat;
  background-position: 50%;
  cursor: col-resize;
}

.gutter.gutter-vertical {
  background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAFAQMAAABo7865AAAABlBMVEVHcEzMzMzyAv2sAAAAAXRSTlMAQObYZgAAABBJREFUeF5jOAMEEAIEEFwAn3kMwcB6I2AAAAAASUVORK5CYII=");
}

.split-grid {
  display: grid;
}

.split-column {
  overflow: auto;
  width: 100%;
}
```

React
```javascript
import Split from "react-split-grid";

function MyComponent() {
  const [columns, setColumns] = useState(`1fr 5px 3fr 5px 1fr`);

  const handleDrag = (direction, track, gridTemplateStyle) => {
    setColumns(gridTemplateStyle);
  };

  return (
      <Split
        gridTemplateColumns={columns}
        onDrag={handleDrag}
        cursor="col-resize"
        render={({ getGridProps, getGutterProps }) => (
          <div className="split-grid" {...getGridProps()}>
            <div className="split-column">
                    COLUMN A (position 0)
            </div>
            <div
              className="gutter gutter-vertical"
              {...getGutterProps("column", 1)}
            />
            <div className="split-column">
               COLUMN B (position 2)
            </div>
            <div
              className="gutter gutter-vertical"
              {...getGutterProps("column", 3)}
            />
            <div className="split-column">
              COLUMN C (position 3)
            </div>
          </div>
        )}
      />
  );
}
```
This may not be the only way to get started, but it worked for me. Hopefully this helps other people not have to spend so much time.
