### ISSUE TITLE
Doesn't work in case of css media queries!

### ISSUE THREAD

**Issue by learnwithsumit** [nathancahill/split#545]
It seems that, splitting not working in case of CSS media queries. Please check the below example:

```css
* {
box-sizing: border-box;
margin: 0;
padding: 0;
}
.grid > div {
border: 1px solid #f5f5f5;
display: flex;
align-items: center;
justify-content: center;
}
.grid {
height: 100vh;
display: grid;
}

@media (min-width: 1024px) {
.grid {
    grid-template-columns: 150px 1fr 5px 1fr;
    grid-template-rows: 32px 1fr;
}
.topbar {
    grid-column: 1/-1;
}
.column-gutter {
    cursor: col-resize;
    grid-column: 3;
}
}
```

```html
<div class="grid">
      <div class="topbar"></div>
      <div class="explorer"></div>
      <div class="editor"></div>
      <div class="column-gutter"></div>
      <div class="chapters"></div>
    </div>
```

```javascript
Split({
        minSize: 400,
        columnGutters: [
          {
            track: 2,
            element: document.querySelector(".column-gutter"),
          },
        ],
      });
